--- 
title: "Asher's Cookbook"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: katelyn98/RecipesSite
description: "This is a collection of Asher's favorite recipes and wine pairings"
---

# Happy Birthday {-}

Cooking delicious, savory (and sometimes sweet) platters takes talent and many times multiple attempts. Finding recipes for these platters is not easy ever since online advertising took over the internet. Recipe sites out there are full of dynamic, annoying ads that cover portions of the ingredients list or the instructions. Furthermore, these websites with recipes are pages long of unnecessary pictures and stories about the platter. This really annoys Asher...thus, I have created a website that is AD FREE, STORY FREE, and CONCISE. (It also started to really annoy me while I was trying to find our recipes to add to this cookbook). Some recipes have not been filled in yet and all recipes will eventually get one picture to show off what Asher cooked. [Work in progress :)] 

## Special Note {-}

Happy Birthday Asher! In hopes to save you stress while you are cooking all these wonderful meals, I present to you Asher's Cookbook (asherscooking.com). You have cooked such delicious meals for me that I never even knew existed. I look forward to cooking these meals with you in the future - this time without all the annoying advertisements! You're always going to be a Michelin Star Chef in my heart! Hugs and kisses ~ Katelyn <3 

